name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  db_sql_query:
    path: ../packages/db_sql_query
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  db_sql_generator:
    path: ../
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true