targets:
  $default:
    builders:
      model_builder:
        enabled: true

builders:
  model_builder:
    import: "package:db_sql_generator/builder.dart"
    builder_factories: ["modelBuilder"]
    build_extensions: { ".dart": [".model_builder.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]