name: db_sql_generator
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.1
  source_gen: ^1.4.0
  db_sql_annotation:
    path: packages/db_sql_annotation
  dart_style: ^2.3.2
  code_builder: ^4.7.0

dev_dependencies:
  lints: ^2.0.1